POST https://prymaze-comics.firebaseio.com/mycomics.json
Content-Type: application/json

{
    "genres": "Action, Scene",
    "title": "Spider-Man Facsimile Edition (2020) #1",
    "publisher": "German Perita",
    "writer": "David Peter",
    "imageUrl": "https://i.annihil.us/u/prod/marvel/i/mg/6/50/5f2c342578db1/portrait_uncanny.jpg",
    "publishedDate": "August 19, 2020",
    "summary": "Celebrating the 30th Anniversary of Spider-Man #1 In 1990, superstar AMAZING SPIDER-MAN artist Todd McFarlane wanted to stretch his creative muscles as a writer — and the result was a brand-new SPIDER-MAN book that needed no superlative! Boasting one of the most famous comic-book covers ever drawn, the record-breaking first issue sold over two million copies — and inside, McFarlane’s Spider-Man looked more extraordinary than ever. But why has Spidey’s classic foe the Lizard begun a brutal killing spree? As the pounding drums spell doom, the torment is only beginning for Spider-Man and Dr. Curt Connors! It’s one of the all-time great Marvel comic books, boldly re-presented in its original form, ads and all! Reprinting SPIDER-MAN (1990) #1."
}

###
GET  https://prymaze-comics.firebaseio.com/mycomics.json